canton {
  participants {
    sandbox {
      storage {
        type = memory
        config {
          properties {
            url = "jdbc:h2:mem:sandbox;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
          }
        }
      }
    }
  }
}
